services:
  mariadb:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: BestPasswordEver:)
      MARIADB_DATABASE: logisticam
    volumes:
      - ./bdd/db:/var/lib/mysql
      - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql