# Generated by Django 4.2.20 on 2025-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Achat', 'Achat'), ('Vente', 'Vente')], default='Achat', max_length=16),
        ),
    ]
