# Generated by Django 4.2.20 on 2025-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Achat', 'Achat'), ('Vente', 'Vente')], default='Vente', max_length=16),
        ),
    ]
