# Generated by Django 4.2.20 on 2025-06-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.client'),
        ),
    ]
