# Generated by Django 4.2.20 on 2025-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_transaction_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
