# Generated by Django 4.2.20 on 2025-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stock_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('Client', 'Client'), ('Fournisseur', 'Fournisseur')], default='Client', max_length=255),
        ),
    ]
